<?php
/**
 * @var $block \DavidUmoh\Auth0\Block\Auth
 */
?>
<script >
    'use strict';
    var auth0Config =<?php echo json_encode($block->getConfigData()); ?>;


    require(['jquery'],function($){

        $(function(){
            var config = auth0Config;

            var lock = new Auth0Lock(
                config.clientId,
                config.domain, {
                    auth: {
                        redirectUrl: config.callbackUrl,
                        responseType: 'code',
                        params: {
                            scope: 'openid email' // Learn about scopes: https://auth0.com/docs/scopes
                        }
                    }
                });

         $('li.authorization-link > a, ul.header.links > li > a').click(function(e) {

             e.preventDefault();
             lock.show();
         });




     });
 });
</script>
