<?php
/**
 * @var $block \DavidUmoh\Auth0\Block\Auth
 */
?>
<script >
    'use strict';
    var auth0Config =<?php echo json_encode($block->getConfigData()); ?>;
    var oAuthScope = auth0Config.scope?auth0Config.scope: 'openid email profile';
    var linkSelector = auth0Config.linkSelector?auth0Config.linkSelector:null;

    require(['jquery','auth0Lock'],function($,lock){

        $(function(){
            var config = auth0Config;
            
            var myLock = new lock(
                config.clientId,
                config.domain, {
                    auth: {
                        redirectUrl: config.callbackUrl,
                        responseType: 'code',
                        params: {
                            scope:oAuthScope// Learn about scopes: https://auth0.com/docs/scopes
                        }
                    }
                });

         if(linkSelector){
            $(linkSelector).click(function(e) {

                e.preventDefault();
                myLock.show();
            });
         }       
         

     });
 });
</script>
